"""empty message

Revision ID: 1b56f53f50d6
Revises: 1d0b18309a78
Create Date: 2020-10-19 22:52:06.805040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b56f53f50d6'
down_revision = '1d0b18309a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Artistid', sa.Integer(), nullable=False),
    sa.Column('Venueid', sa.Integer(), nullable=False),
    sa.Column('Showdatetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
